### ISSUE TITLE
Can't run the app

### ISSUE THREAD

**Issue by uivil** [s-victor/TinyPedal#7]
This is the traceback:
```
Traceback (most recent call last):
  File "D:\TinyPedal\run.py", line 61, in <module>
    load_tinypedal()
  File "D:\TinyPedal\run.py", line 53, in load_tinypedal
    start_tray(root)
  File "D:\TinyPedal\tinypedal\about.py", line 106, in start_tray
    from tinypedal.tray import TrayIcon
  File "D:\TinyPedal\tinypedal\tray.py", line 28, in <module>
    from .load_func import module
  File "D:\TinyPedal\tinypedal\load_func.py", line 26, in <module>
    from .realtime_delta import DeltaTime
  File "D:\TinyPedal\tinypedal\realtime_delta.py", line 27, in <module>
    from .readapi import info, chknm, cs2py, state, combo_check
  File "D:\TinyPedal\tinypedal\readapi.py", line 40, in <module>
    info = SimInfoAPI("")
  File "D:\TinyPedal\pyRfactor2SharedMemory\sharedMemoryAPI.py", line 32, in __init__
    rF2data.SimInfo.__init__(self, input_pid)
  File "D:\TinyPedal\pyRfactor2SharedMemory\rF2data.py", line 697, in __init__
    self._rf2_tele = mmap.mmap(0, ctypes.sizeof(rF2Telemetry), f"$rFactor2SMMP_Telemetry${input_pid}")
PermissionError: [WinError 5] Access is denied
Exception ignored in: <function SimInfoAPI.__del__ at 0x0000026087C43130>
Traceback (most recent call last):
  File "D:\TinyPedal\pyRfactor2SharedMemory\sharedMemoryAPI.py", line 288, in __del__
    self.close()
  File "D:\TinyPedal\pyRfactor2SharedMemory\rF2data.py", line 709, in close
    self._rf2_tele.close()
AttributeError: 'SimInfoAPI' object has no attribute '_rf2_tele'
```

I get the same traceback  in both cases (exe and `python run.py`)

**Comment by s-victor** [comment]
Hi, sorry this is not reproducible on my side, and there is no similar reports. From quick web search, it may relate to system file permission or missing file dependency, which may not be related to this app.
